IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'company')
BEGIN
	CREATE TABLE company (
		Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
		Name varchar(256) NOT NULL,
		Code varchar(32) NOT NULL
	);
END

ALTER TABLE route
ADD CONSTRAINT FK_Route_CompanyId FOREIGN KEY (CompanyId) REFERENCES company(Id);